server.port: 8081

spring.datasource.url: jdbc:mysql://localhost:3306/local
spring.datasource.username: root
spring.datasource.password: root1234
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver